Eski/WebOdev/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebOdev.Models
{
    public class Kullanici
    {
        public int KullaniciID { get; set; }
        public string Adi { get; set; }
        public string Sifre { get; set; }
    }
}

Eski/WebOdev/Models/Oyun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebOdev.Models
{
    public class Oyun
    {
        [Key]
        public int OyunID { get; set; }
        public string Adi { get; set; }
        public int Fiyat { get; set; }
        public string SistemGereksinimleri { get; set; }

        public virtual ICollection<Yorum> Yorumlar { get; set; }
    }
}

Eski/WebOdev/Models/Yorum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebOdev.Models
{
    public class Yorum
    {
        public int YorumID { get; set; }
        public string yorum { get; set; }
        public DateTime Tarih { get; set; }

        public virtual Kullanici Yazar { get; set; }
    }
}

Eski/WebOdev/Models/oyunBaslangic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebOdev.Models
{
    public class oyunBaslangic : System.Data.Entity.DropCreateDatabaseIfModelChanges<oyunContext>
    {
        protected override void Seed(oyunContext context)
        {
            base.Seed(context);
        }
    }
}

Eski/WebOdev/Models/oyunContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebOdev.Models
{
    public class oyunContext : DbContext
    {
        public DbSet<Oyun> Oyun { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Yorum> Yorum { get; set; }
    }
}

Eski/WebOdev/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Eski/WebOdev/Controllers/OyunController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebOdev.Models;

namespace WebOdev.Controllers
{
    public class OyunController : Controller
    {
        private oyunContext db = new oyunContext();

        // GET: Oyun
        public ActionResult Index()
        {
            return View(db.Oyun.ToList());
        }

        // GET: Oyun/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyun oyun = db.Oyun.Find(id);
            if (oyun == null)
            {
                return HttpNotFound();
            }
            return View(oyun);
        }

        // GET: Oyun/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Oyun/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OyunID,Adi,Fiyat,SistemGereksinimleri")] Oyun oyun)
        {
            if (ModelState.IsValid)
            {
                db.Oyun.Add(oyun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oyun);
        }

        // GET: Oyun/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyun oyun = db.Oyun.Find(id);
            if (oyun == null)
            {
                return HttpNotFound();
            }
            return View(oyun);
        }

        // POST: Oyun/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OyunID,Adi,Fiyat,SistemGereksinimleri")] Oyun oyun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oyun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oyun);
        }

        // GET: Oyun/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oyun oyun = db.Oyun.Find(id);
            if (oyun == null)
            {
                return HttpNotFound();
            }
            return View(oyun);
        }

        // POST: Oyun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oyun oyun = db.Oyun.Find(id);
            db.Oyun.Remove(oyun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Eski/WebOdev/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Eski/WebOdev/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Eski/WebOdev/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />

@*<div class="row">
    <div class="jumbotron">
        <h1>Ertan Çakır - G140910054</h1>
    </div>
</div>*@
@*<div class="row">
    
</div>*@
<div class="row">
    <div class="col-md-4">
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Haftanın Oyunu</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">En Çok Alınanlar</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">Son Kullanıcı Yorumları</h3>
                </div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Oyunlar</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
</div>

Eski/WebOdev/Views/Oyun/Create.cshtml
@model WebOdev.Models.Oyun

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Oyun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SistemGereksinimleri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SistemGereksinimleri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SistemGereksinimleri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eski/WebOdev/Views/Oyun/Delete.cshtml
@model WebOdev.Models.Oyun

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Oyun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistemGereksinimleri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistemGereksinimleri)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Eski/WebOdev/Views/Oyun/Details.cshtml
@model WebOdev.Models.Oyun

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Oyun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SistemGereksinimleri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SistemGereksinimleri)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OyunID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Eski/WebOdev/Views/Oyun/Edit.cshtml
@model WebOdev.Models.Oyun

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Oyun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OyunID)

        <div class="form-group">
            @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SistemGereksinimleri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SistemGereksinimleri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SistemGereksinimleri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eski/WebOdev/Views/Oyun/Index.cshtml
@model IEnumerable<WebOdev.Models.Oyun>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SistemGereksinimleri)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Adi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fiyat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SistemGereksinimleri)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OyunID }) |
            @Html.ActionLink("Details", "Details", new { id=item.OyunID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OyunID })
        </td>
    </tr>
}

</table>

Eski/WebOdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mithrill.com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Oyunlar", "Index", "Oyun")</li>
                </ul>
                <span class="col-md-2"></span>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Oyun Ara">
                    </div>
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dil <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">TR</a></li>
                            <li><a href="#">EN</a></li>
                        </ul>
                    </li>
                    <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span><span class="badge">1</span></a></li>
                    <li><button type="button" class="btn btn-info navbar-btn">Kayıt Ol</button></li>
                    <li><button type="button" class="btn btn-success navbar-btn">Giriş Yap</button></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                <div class="row">
                    <hr>
                    <div class="col-lg-12">
                        <div class="col-md-8">
                            @Html.ActionLink("Hakkımızda", "About", "Home") | @Html.ActionLink("İletişim", "Contact", "Home")
                        </div>
                        <div class="col-md-4">
                            <p class="muted pull-right">© @DateTime.Now.Year - @Html.ActionLink("Ertan Çakır", "Contact", "Home")</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>